
//Get All the Posts
GET http://localhost:8095/posts/getAllPosts
Content-Type: application/json

//Get a post by postId
###
GET http://localhost:8095/posts/getPostById/:postId
Content-Type: application/json


//Get all posts from a username
###
GET http://localhost:8095/posts/getAllByUsername/:username
Content-Type: application/json


//Create a Post using an access token (do /get-token in URL)
###
POST http://localhost:8095/posts/createPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjZmYjc2NzdjZGNkODAxYWRlM2UzNiIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ1c2VybmFtZTIiLCJpYXQiOjE3Mjc0NjQyNzMsImV4cCI6MTcyNzQ2Nzg3M30.cgff-lYByEQAkhwVn6q3yF5axIoCLEvzslih1eaqQlA

{
  "content": "This is a test post.",
  "imageId": "60d21b4667d0d8992e610c85"
}


//Create post without an access token (should fail)
###
POST http://localhost:8095/posts/createPost
Content-Type: application/json

{
  "content": "This post should fail due to missing token.",
  "imageId": "60d21b4667d0d8992e610c85"
}


//Delete a Post
###
DELETE http://localhost:8095/posts/deletePost/:id
Content-Type: application/json 


//Update a Post
###
PUT http://localhost:8095/posts/updatePost/:id
Accept: application/json 

###
