
//Get All the Posts
GET http://localhost:8095/posts/getAllPosts
Content-Type: application/json

//Get a post by postId
###
GET http://localhost:8095/posts/getPostById/:postId
Content-Type: application/json


//Get all posts from a username
###
GET http://localhost:8095/posts/getAllByUsername/:username
Content-Type: application/json


//Create a Post using an access token (do /get-token in URL)
###
POST http://localhost:8095/posts/createPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjZmYjc2NzdjZGNkODAxYWRlM2UzNiIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ1c2VybmFtZTIiLCJpYXQiOjE3Mjc0NjQyNzMsImV4cCI6MTcyNzQ2Nzg3M30.cgff-lYByEQAkhwVn6q3yF5axIoCLEvzslih1eaqQlA

{
  "content": "This is a test post.",
  "imageId": "60d21b4667d0d8992e610c85"
}


//Create post without an access token (should fail)
###
POST http://localhost:8095/posts/createPost
Content-Type: application/json

{
  "content": "This post should fail due to missing token.",
  "imageId": "60d21b4667d0d8992e610c85"
}


// Delete a Post using a valid access token
###
DELETE http://localhost:8095/posts/deletePost/66ff3de4679ebb25154dc18f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmYwNGE1NDQ2OTQ1NzA0NGM1ZTExYiIsImVtYWlsIjoidXNlcm5hbWVAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ0ZXN0bmFtZTIiLCJpYXQiOjE3Mjg0MDU3NjMsImV4cCI6MTcyODQwOTM2M30.jnfz1IH-vBrCYwQZ-4tsdFONcKnnFnocHHB0tezzr9o

// No body required for this request

// Try to delete a Post without an access token (should fail)
###
DELETE http://localhost:8095/posts/deletePost/6705610916fe74a24a7d6e16

// No Authorization header
// No body required for this request

// Try to delete a Post using an invalid token (should fail)
###
DELETE http://localhost:8095/posts/deletePost/66ff3de4679ebb25154dc18f
Authorization: Bearer invalid_or_expired_token

// No body required for this request

// Try to delete a Post that is not owned by the authenticated user (should fail)
###
DELETE http://localhost:8095/posts/deletePost/66f703e4465d2875b5d7a08e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmYwNGE1NDQ2OTQ1NzA0NGM1ZTExYiIsImVtYWlsIjoidXNlcm5hbWVAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ0ZXN0bmFtZTIiLCJpYXQiOjE3Mjg0MDU3NjMsImV4cCI6MTcyODQwOTM2M30.jnfz1IH-vBrCYwQZ-4tsdFONcKnnFnocHHB0tezzr9o

// No body required for this request


// Update a Post using a valid access token
###
PUT http://localhost:8095/posts/updatePost/67080309cc875d865137601a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmYwNGE1NDQ2OTQ1NzA0NGM1ZTExYiIsImVtYWlsIjoidXNlcm5hbWVAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ0ZXN0bmFtZTIiLCJpYXQiOjE3Mjg1NzgwMjQsImV4cCI6MTcyODU4MTYyNH0.kNlxMWBxq6oRkaQmTB8bjThD1GtsGotywIe6VMOYqF4

{
  "content": "Updated post content",
  "imageUri": "newImageUri"
}
 
// Try to update a Post without an access token (should fail)
###
PUT http://localhost:8095/posts/updatePost/67080309cc875d865137601a
Content-Type: application/json

{
  "content": "This update should fail due to missing token."
}

// Try to update a Post using an invalid token (should fail)
###
PUT http://localhost:8095/posts/updatePost/67080309cc875d865137601a
Content-Type: application/json
Authorization: Bearer invalid_or_expired_token

{
  "content": "This update should fail due to invalid token."
}

// Try to update a Post that is not owned by the authenticated user (should fail)
###
PUT http://localhost:8095/posts/updatePost/66f7051e465d2875b5d7a0b5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmYwNGE1NDQ2OTQ1NzA0NGM1ZTExYiIsImVtYWlsIjoidXNlcm5hbWVAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ0ZXN0bmFtZTIiLCJpYXQiOjE3Mjg1NzgwMjQsImV4cCI6MTcyODU4MTYyNH0.kNlxMWBxq6oRkaQmTB8bjThD1GtsGotywIe6VMOYqF4

{
  "content": "This update should fail due to unauthorized user."
}

// Attempt to create a Post with a custom flagged word "carrot" (should censor)
###
POST http://localhost:8095/posts/createPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTJiMGE3NDNkOTllZTIxNGRlY2I1NiIsImVtYWlsIjoicGFzQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidGVzdHRlc3QiLCJpYXQiOjE3Mjk2MTUyNTEsImV4cCI6MTcyOTYxODg1MX0.wOMft5s-Nm4lBk73RrPjCxxabCySInrkmsvGIrEgWzg

{
  "content": "I love broccoli!",
  "imageUri": "60d21b4667d0d8992e610c85"
}

###
