POST http://localhost:8095/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8095/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8095/user/getAll
Content-Type: application/json


// Update a User using a valid access token
### Edit User Information
PUT http://localhost:8095/user/editUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZmYwNGE1NDQ2OTQ1NzA0NGM1ZTExYiIsImVtYWlsIjoidXNlcm5hbWVAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ0ZXN0bmFtZTIiLCJpYXQiOjE3Mjg2NzQ4MzksImV4cCI6MTcyODY3ODQzOX0.HJPtsImfj3JbD_eDT3Gs_X5b2a2qJjh-jhPYetUfUAE

{
  "username": "updatedUsername",
  "email": "updatedemail@gmail.com",
  "password": "newPassword123",
  "biography": "This is my updated bio."
}



###
POST http://localhost:8095/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8095/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8095/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8095/user/deleteAll

###
DELETE http://localhost:8095/user/deleteById/66ec5a2dd78bf612a9821748/66ec5a2dd78bf612a9821748

### Delete a user by ID
DELETE http://localhost:8095/user/deleteById/66f20976796cd5ea93c0bd53
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjIwOTc2Nzk2Y2Q1ZWE5M2MwYmQ1MyIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ1c2VybmFtZSIsImlhdCI6MTcyNzE0MTkzNywiZXhwIjoxNzI3MTQ1NTM3fQ.uNH1nfGZnbstMFeI3FifQ7-8Q1PgGcKbIUv3CWMlzi8
Content-Type: application/json

### Get user by username
GET http://localhost:8095/user/getUserByUsername/jacobb12345